clean: Remove all core configurations and README sections
codacy/chart pull request #558
Opened 2020-09-04 11:28 UTC by lolgab

2020-09-04 12:45 UTC, lolgab commented
There are still some dynamoDB things in the repository.
Not sure they are part of core, tho.

2020-09-04 13:31 UTC, franciscodua approved these changes

2020-09-05 19:25 UTC, pauloribeiro-codacy submitted a review, later dismissed
The only change that affects the documentation is the removal of the block in the `values-production.yaml` file. It will be published on the next release of the chart. :+1:

2020-09-08 08:52 UTC, rtfpessoa commented
DynamoDB should only be used by core, and you should also update the requirements.lock file probably. The rest looks fine.

2020-09-08 13:58 UTC, lolgab commented
@rtfpessoa I removed all the DynamoDB parts.
About the `requirements.lock`, it is no more committed in the repository since https://github.com/codacy/chart/pull/393
Should I change the minimum codacy-website version to the first one not using core, right? Same thing should apply for other components that were using core. Correct?

2020-09-08 15:04 UTC, h314to requested changes

2020-09-08 15:04 UTC, h314to commented on docs/infrastructure/EKS/backend/variables.tf
> -  description = "Project tag to add to s3 and dynamodb names"
please don't delete. See comment above

2020-09-08 15:04 UTC, h314to commented on docs/infrastructure/EKS/backend/state_and_lock.tf
> -resource "aws_dynamodb_table" "lock" {
Please keep the lock table

2020-09-08 15:04 UTC, h314to commented on docs/infrastructure/EKS/backend/outputs.tf
> -
Please don't remove

2020-09-08 15:04 UTC, h314to commented on docs/infrastructure/EKS/aws-terraform-minimum-admin-policy.json
> -    {
This shouldn't be removed

2020-09-08 15:04 UTC, h314to commented on docs/infrastructure/EKS/main/config.tf
> -  #  dynamodb_table = "codacy-terraform-lock"
please don't remove this

2020-09-08 15:07 UTC, h314to commented
> DynamoDB should only be used by core, and you should also update the requirements.lock file probably. The rest looks fine.

DynamoDB is used by Terraform for state locking. A table is created specifically for that purpose. See here for further details: https://www.terraform.io/docs/backends/types/s3.html

2020-09-08 16:36 UTC, pedrocodacy approved these changes
pending on a review from @h314to to confirm that we are not messing with dynamo anymore

2020-09-08 16:44 UTC, h314to approved these changes

2020-09-08 16:46 UTC, merged